### ISSUE TITLE
second proposer does not continue chain after submitPeriod()

### ISSUE THREAD

**Issue by johannbarbie** [parsec-labs/parsec-node#20]
## Situation:
slot 0: down
slot 1: see trace below

- at block 32 - slot 0 did not submit
- at Block 64 - round 0, checkBridge() called, returned 0
- at Block 64 - round 1, checkBridge() called, period submitted

## Expectation:
period should be submitted, then validator should continue to block 65.

```
I[07-09|05:59:31.166] enterNewRound(64/0). Current: 64/0/RoundStepNewHeight module=consensus height=64 round=0
I[07-09|05:59:31.166] enterPropose(64/0). Current: 64/0/RoundStepNewRound module=consensus height=64 round=0
I[07-09|05:59:31.166] enterPropose: Our turn to propose            module=consensus height=64 round=0 proposer=C8E33A7EFABEF8C35644A944ECE00AE121C727AD privValidator="PrivValidator{C8E33A7EFABEF8C35644A944ECE00AE121C727AD LH:63, LR:0, LS:3}"
{ signedTx: 
   { messageHash: '0x4d3a6c3e6b77c46fb3e36775fc97cccb38f87bea1241267553ca19a13038349f',
     v: '0x2c',
     r: '0x62675a2c538c5998efbfed36e1063071b5b153f174f88e356b828ecccc231c24',
     s: '0x7707b319abc2e351dbf25360036189d330d8ac281677c56cdb79805d6eae245',
     rawTransaction: '0xf8c902843b9aca008302733b94099303c83fda47570b255a8fcebf5f8dd86e015e80b864877c4f6e0000000000000000000000000000000000000000000000000000000000000001f412e11048b82e1411ae6ce465594cd3c4cc1bfc18039712172f81ecf17f5b72572063b72ee42c733d49e989868bab97acbcb5edd5db9d1dcd5ba5ce908441462ca062675a2c538c5998efbfed36e1063071b5b153f174f88e356b828ecccc231c24a007707b319abc2e351dbf25360036189d330d8ac281677c56cdb79805d6eae245' } }
{ txResult: 
   Promise {
     <pending>,
     _events: undefined,
     emit: [Function: emit],
     on: [Function: on],
     once: [Function: once],
     off: [Function: removeListener],
     listeners: [Function: listeners],
     addListener: [Function: on],
     removeListener: [Function: removeListener],
     removeAllListeners: [Function: removeAllListeners] } }
E[07-09|05:59:31.522] previous Period could not be found in Bridge, waiting... module=consensus height=64 round=0 height=64
I[07-09|05:59:34.166] Timed out                                    module=consensus dur=3s height=64 round=0 step=RoundStepPropose
I[07-09|05:59:34.166] enterPrevote(64/0). Current: 64/0/RoundStepPropose module=consensus 
I[07-09|05:59:34.166] enterPrevote: ProposalBlock is nil           module=consensus height=64 round=0
I[07-09|05:59:34.169] Signed and pushed vote                       module=consensus height=64 round=0 vote="Vote{0:C8E33A7EFABE 64/00/1(Prevote) 000000000000 /4060306D3E6D.../ @ 2018-07-09T05:59:34.167Z}" err=null
I[07-09|05:59:34.172] Added to prevote                             module=consensus vote="Vote{0:C8E33A7EFABE 64/00/1(Prevote) 000000000000 /4060306D3E6D.../ @ 2018-07-09T05:59:34.167Z}" prevotes="VoteSet{H:64 R:0 T:1 +2/3::0:000000000000(1) BA{1:x} map[]}"
I[07-09|05:59:34.172] enterPrecommit(64/0). Current: 64/0/RoundStepPrevote module=consensus height=64 round=0
I[07-09|05:59:34.172] enterPrecommit: +2/3 prevoted for nil.       module=consensus height=64 round=0
I[07-09|05:59:34.174] Signed and pushed vote                       module=consensus height=64 round=0 vote="Vote{0:C8E33A7EFABE 64/00/2(Precommit) 000000000000 /531D30003E30.../ @ 2018-07-09T05:59:34.172Z}" err=null
I[07-09|05:59:34.176] Added to precommit                           module=consensus vote="Vote{0:C8E33A7EFABE 64/00/2(Precommit) 000000000000 /531D30003E30.../ @ 2018-07-09T05:59:34.172Z}" precommits="VoteSet{H:64 R:0 T:2 +2/3::0:000000000000(1) BA{1:x} map[]}"
I[07-09|05:59:34.176] enterNewRound(64/1). Current: 64/0/RoundStepPrecommit module=consensus height=64 round=1
I[07-09|05:59:34.176] Resetting Proposal info                      module=consensus height=64 round=1
I[07-09|05:59:34.176] enterPropose(64/1). Current: 64/1/RoundStepNewRound module=consensus height=64 round=1
I[07-09|05:59:34.176] enterPropose: Our turn to propose            module=consensus height=64 round=1 proposer=C8E33A7EFABEF8C35644A944ECE00AE121C727AD privValidator="PrivValidator{C8E33A7EFABEF8C35644A944ECE00AE121C727AD LH:64, LR:0, LS:3}"
E[07-09|05:59:34.500] previous Period could not be found in Bridge, waiting... module=consensus height=64 round=1 height=64
I[07-09|05:59:37.677] Timed out                                    module=consensus dur=3.5s height=64 round=1 step=RoundStepPropose
I[07-09|05:59:37.677] enterPrevote(64/1). Current: 64/1/RoundStepPropose module=consensus 
I[07-09|05:59:37.677] enterPrevote: ProposalBlock is nil           module=consensus height=64 round=1
I[07-09|05:59:37.679] Signed and pushed vote                       module=consensus height=64 round=1 vote="Vote{0:C8E33A7EFABE 64/01/1(Prevote) 000000000000 /08BA59902529.../ @ 2018-07-09T05:59:37.677Z}" err=null
I[07-09|05:59:37.682] Added to prevote                             module=consensus vote="Vote{0:C8E33A7EFABE 64/01/1(Prevote) 000000000000 /08BA59902529.../ @ 2018-07-09T05:59:37.677Z}" prevotes="VoteSet{H:64 R:1 T:1 +2/3::0:000000000000(1) BA{1:x} map[]}"
I[07-09|05:59:37.682] enterPrecommit(64/1). Current: 64/1/RoundStepPrevote module=consensus height=64 round=1
I[07-09|05:59:37.682] enterPrecommit: +2/3 prevoted for nil.       module=consensus height=64 round=1
I[07-09|05:59:37.684] Signed and pushed vote                       module=consensus height=64 round=1 vote="Vote{0:C8E33A7EFABE 64/01/2(Precommit) 000000000000 /2CB2E066E35E.../ @ 2018-07-09T05:59:37.682Z}" err=null
I[07-09|05:59:37.687] Added to precommit                           module=consensus vote="Vote{0:C8E33A7EFABE 64/01/2(Precommit) 000000000000 /2CB2E066E35E.../ @ 2018-07-09T05:59:37.682Z}" precommits="VoteSet{H:64 R:1 T:2 +2/3::0:000000000000(1) BA{1:x} map[]}"
I[07-09|05:59:37.687] enterNewRound(64/2). Current: 64/1/RoundStepPrecommit module=consensus height=64 round=2
I[07-09|05:59:37.687] Resetting Proposal info                      module=consensus height=64 round=2
I[07-09|05:59:37.687] enterPropose(64/2). Current: 64/2/RoundStepNewRound module=consensus height=64 round=2
I[07-09|05:59:37.687] enterPropose: Our turn to propose            module=consensus height=64 round=2 proposer=C8E33A7EFABEF8C35644A944ECE00AE121C727AD privValidator="PrivValidator{C8E33A7EFABEF8C35644A944ECE00AE121C727AD LH:64, LR:1, LS:3}"
submitPeriod { id: 1,
  owner: '0x8db6B632D743aef641146DC943acb64957155388',
  stake: '200000100',
  signer: '0x448BE90ee55F49e15b20e0c43A49CeB59B67498A',
  tendermint: '0xf92b65eeaef001255bac62e31ae868dde7b23c1e1957dc315c87a7902d061469',
  activationEpoch: '0',
  newOwner: '0x0000000000000000000000000000000000000000',
  newStake: '0',
  newSigner: '0x0000000000000000000000000000000000000000',
  newTendermint: '0x0000000000000000000000000000000000000000000000000000000000000000' } Result {
  '0': '0x0000000000000000000000000000000000000000000000000000000000000000',
  '1': '0',
  '2': '0',
  '3': '0',
  '4': '0',
  '5': '0',
  parent: '0x0000000000000000000000000000000000000000000000000000000000000000',
  height: '0',
  parentIndex: '0',
  slot: '0',
  timestamp: '0',
  reward: '0' }
(node:17376) UnhandledPromiseRejectionWarning: Error: This socket is closed
    at Socket._writeGeneric (net.js:729:18)
    at Socket._write (net.js:783:8)
    at doWrite (_stream_writable.js:397:12)
    at writeOrBuffer (_stream_writable.js:383:5)
    at Socket.Writable.write (_stream_writable.js:290:11)
    at Socket.write (net.js:707:40)
    at Connection._write (/usr/local/share/.config/yarn/global/node_modules/abci/src/connection.js:75:17)
    at <anonymous>
(node:17376) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 5)
(node:17376) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
E[07-09|05:59:38.368] Stopping abci.socketClient for error: EOF    module=abci-client connection=consensus
I[07-09|05:59:38.368] Stopping socketClient                        module=abci-client connection=consensus impl=socketClient
I[07-09|05:59:41.687] Timed out                                    module=consensus dur=4s height=64 round=2 step=RoundStepPropose
```

**Comment by johannbarbie** [comment]
after restart node proposed block and continued
