### ISSUE TITLE
timeout starting tendermint node

### ISSUE THREAD

**Issue by johannbarbie** [parsec-labs/parsec-node#23]
when syncing to big heights:

```
Height: 223
I[07-09|09:15:09.627] Applying block                               module=consensus height=223
I[07-09|09:15:09.707] Executed block                               module=consensus height=223 validTxs=0 invalidTxs=0
Height: 224
I[07-09|09:15:09.747] Applying block                               module=consensus height=224
error starting tendermint node:
Error: Timed out while waiting
    at /usr/local/share/.config/yarn/global/node_modules/tendermint-node/src/index.js:119:15
    at <anonymous>
(node:27376) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'synced' of undefined
    at Promise (/usr/local/share/.config/yarn/global/node_modules/lotion/index.js:199:26)
    at <anonymous>
(node:27376) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 31)
(node:27376) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
I[07-09|09:15:09.827] Executed block                               module=consensus height=224 validTxs=1 invalidTxs=0
Height: 225
I[07-09|09:15:09.867] Applying block                               module=consensus height=225
I[07-09|09:15:09.947] Executed block                               module=consensus height=225 validTxs=1 invalidTxs=0
Height: 226
```

**Comment by sunify** [comment]
Probably we should just remove timeout. It just doesn't make any sense
